# Font
font_family      Iosevka Nerd Font Mono
font_size        12

# Bell
enable_audio_bell no

# Window
window_padding_width 0
hide_window_decorations yes

# Tab bar
tab_bar_style hidden

# Color scheme - TokyoNight
include tokyonight_night.conf
