return {
	"miversen33/sunglasses.nvim",
	config = true,
	opts = {
		filter_type = "TINT",
		filter_percent = 0.03,
		excluded_filetypes = {
			"dashboard",
			"lspsagafinder",
			"packer",
			"checkhealth",
			"mason",
			-- "NvimTree",
			-- "neo-tree",
			"plugin",
			"lazy",
			"TelescopePrompt",
			"alpha",
			"toggleterm",
			"sagafinder",
			"better_term",
			"fugitiveblame",
			"starter",
			"NeogitPopup",
			"NeogitStatus",
			"DiffviewFiles",
			"DiffviewFileHistory",
			"DressingInput",
			"spectre_panel",
			"zsh",
			"registers",
			"startuptime",
			"OverseerList",
			"Outline",
			"Navbuddy",
			"noice",
			"notify",
			"saga_codeaction",
			"sagarename",
		},
	},
}
